<#
.SYNOPSIS
  Provision TEST database and prepare Render/Cloudflare configuration values.

.DESCRIPTION
  1. Creates UletiSmenuDb_Test on the existing Azure SQL server (if missing).
  2. Builds a TEST connection string from the LIVE App Service setting.
  3. Writes secrets to scripts/.test-env-secrets.local (gitignored).
  4. Prints manual steps for Render and Cloudflare Pages.

.PARAMETER ResourceGroup
.PARAMETER SqlServerName
.PARAMETER ApiAppName
  LIVE Azure App Service used to read the SQL connection string template.
.PARAMETER DatabaseName

.EXAMPLE
  .\scripts\setup-test-env.ps1 -SqlServerName uletismenu-staging-sql
#>
[CmdletBinding()]
param(
    [string] $ResourceGroup = "rg-uletismenu-staging",
    [Parameter(Mandatory = $true)]
    [string] $SqlServerName,
    [string] $ApiAppName = "api-staging-uletismenu",
    [string] $DatabaseName = "UletiSmenuDb_Test"
)

$ErrorActionPreference = "Stop"

if (-not (az account show 2>$null)) { throw "Run: az login" }

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$secretsFile = Join-Path $scriptDir ".test-env-secrets.local"

Write-Host "=== UletiSmenu TEST environment setup ===" -ForegroundColor Cyan
Write-Host ""

& (Join-Path $scriptDir "provision-test-database.ps1") `
    -ResourceGroup $ResourceGroup `
    -SqlServerName $SqlServerName `
    -DatabaseName $DatabaseName

$liveConnectionString = az webapp config appsettings list `
    --resource-group $ResourceGroup `
    --name $ApiAppName `
    --query "[?name=='ConnectionStrings__UletiSmenu'].value | [0]" `
    -o tsv

if (-not $liveConnectionString) {
    throw "Could not read ConnectionStrings__UletiSmenu from $ApiAppName."
}

$testConnectionString = $liveConnectionString -replace '(?i)(Initial Catalog|Database)\s*=\s*[^;]+', "`$1=$DatabaseName"

$secrets = @(
    "# Generated by setup-test-env.ps1 - do not commit",
    "# Copy ConnectionStrings__UletiSmenu into Render (uletismenu-api-test)",
    "",
    "ConnectionStrings__UletiSmenu=$testConnectionString",
    "",
    "# Optional: TEST admin seed (only when AdminSeed__Enabled=true on Render)",
    "AdminSeed__Email=admin@test.uletismenu.com",
    "AdminSeed__Password=CHANGE_ME_STRONG_PASSWORD",
    ""
)

Set-Content -Path $secretsFile -Value $secrets -Encoding UTF8

Write-Host ""
Write-Host "Secrets written to:" -ForegroundColor Green
Write-Host "  $secretsFile"
Write-Host ""
Write-Host "=== Manual steps (Render + Cloudflare) ===" -ForegroundColor Yellow
Write-Host ""
Write-Host "Backend repo (uleti-smenu-backend-git):"
Write-Host "  1. Render Dashboard -> New -> Blueprint"
Write-Host "  2. Connect repo, branch: develop, Blueprint path: render-test.yaml"
Write-Host "  3. Environment -> paste ConnectionStrings__UletiSmenu from secrets file"
Write-Host "  4. Set AdminSeed__Email and AdminSeed__Password (TEST only)"
Write-Host "  5. After deploy, note Render hostname (e.g. uletismenu-api-test.onrender.com)"
Write-Host ""
Write-Host "Frontend repo (uleti-smenu_react):"
Write-Host "  1. Cloudflare Pages -> Create project -> connect develop branch"
Write-Host "  2. Root: uleti-smenu | Build: npm ci; npm run build | Output: dist"
Write-Host "  3. Environment variable: VITE_API_BASE_URL=https://api-test.uletismenu.com"
Write-Host "  4. Custom domain: test.app.uletismenu.com"
Write-Host ""
Write-Host "DNS (Cloudflare):"
Write-Host "  - test.app  CNAME -> your-pages-project.pages.dev"
Write-Host "  - api-test  CNAME -> uletismenu-api-test.onrender.com (grey cloud during setup)"
Write-Host ""
Write-Host "Verify after first deploy:"
Write-Host "  curl https://api-test.uletismenu.com/health"
Write-Host "  curl https://api-test.uletismenu.com/health/ready"
Write-Host "  Open https://test.app.uletismenu.com and register a test user"
